##########################################################
################## 1 all profile share config  ############
##########################################################

containerConfig:
  transfer: 
    enabled: true
    tool: rabbitmq
  memory: 
    enabled: true
    tool: redis
  storage: 
    enabled: true
    tool: mysql
  archive: 
    enabled: true
    tool: mongodb
  
###### spring config  ###################

spring:
  profiles:
    active: development
  ####redis配置
  redis:
  	model: single  ##single,sharded,cluster
  	clusterNodes: 192.168.3.205:7001,192.168.3.205:7002,192.168.3.205:7003,192.168.3.205:7004,192.168.3.205:7005,192.168.3.205:7006
  	commandTimeout: 30
    password: wtx
    expireSeconds: 120
    soTimeout: 60000
    maxAttempts: 3
    maxTotal: 100
    maxIdle: 40
    minIdle: 20
    maxWaitMillis: 3000
  rabbitmq:
    address: 192.168.3.19
    username: admin
    password: admin
    publisherConfirms: false
    virtualHost: /
    queueNames:
      ##格式为:"exchange类型.数据类型.生产者.消费者",   "数据类型"作为exchange,   "生产者.消费者"作为routeKey,  整个作为queue名称,  "-"是yml中的格式, 请忽略
      transferQ: topic.scdata.SC.VLR_EVENT
      defaultQ: topic.defaultQ.defaultE.defaultK
    
    
### mybatis-plus config  #################

---
##########################################################
################### 2 development profile  ################
##########################################################
spring:
  profiles: development
server:
  port: 8081

---

##########################################################
################### 3 production profile  #################
##########################################################
spring:
  profiles: production
server:
  port: 8080