##########################################################
################## 1 all profile share config  ############
##########################################################

container_config:
  transfer: 
    enabled: true
    tool: rabbitmq
  memory: 
    enabled: true
    tool: redis
  storage: 
    enabled: true
    tool: mysql
  archive: 
    enabled: true
    tool: mongodb
server:
  port: 8090
  
### spring config  ###################

spring:
  profiles:
    active: development
  rabbitmq:
    address: 192.168.3.19
    username: admin
    password: admin
    publisherConfirms: true
    queueName: 
      transferQ: scdata.transferE.defaultK
      defaultQ: defaultQ.defaultE
    exchange:
      transferE: scdataE
      defaultE: defaultE
    keys:
      scdataK: scdataK
      defaultK: defaultK
    
### mybatis-plus config  #################

---
##########################################################
################### 2 development profile  ################
##########################################################
spring:
  profiles: development
server:
  port: 8081

---

##########################################################
################### 3 production profile  #################
##########################################################
spring:
  profiles: production
server:
  port: 8080